// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBle3smvwKt3Xy5FuJLBkXSzs10dH9szQ',
    appId: '1:473541341688:web:daac2f40373fb59239260d',
    messagingSenderId: '473541341688',
    projectId: 'firestore-example-778e2',
    authDomain: 'firestore-example-778e2.firebaseapp.com',
    storageBucket: 'firestore-example-778e2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR2LWqKh5j_a3jvZQT_9L-YIgoxLsSf8E',
    appId: '1:473541341688:android:a8e4030070ef497739260d',
    messagingSenderId: '473541341688',
    projectId: 'firestore-example-778e2',
    storageBucket: 'firestore-example-778e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-ObBTXC0ZHp_p6HFzqac2IhXVmx-88Gs',
    appId: '1:473541341688:ios:0d037e6ae31cb88d39260d',
    messagingSenderId: '473541341688',
    projectId: 'firestore-example-778e2',
    storageBucket: 'firestore-example-778e2.appspot.com',
    iosClientId: '473541341688-9hrd09aicji4tnofvofb4mnte7rb8soa.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestoreExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-ObBTXC0ZHp_p6HFzqac2IhXVmx-88Gs',
    appId: '1:473541341688:ios:0d037e6ae31cb88d39260d',
    messagingSenderId: '473541341688',
    projectId: 'firestore-example-778e2',
    storageBucket: 'firestore-example-778e2.appspot.com',
    iosClientId: '473541341688-9hrd09aicji4tnofvofb4mnte7rb8soa.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestoreExample',
  );
}
